#!/usr/bin/env python3
"""
Calibrate XGBoost model probabilities using Platt scaling (sigmoid calibration).

This script:
1. Loads the feature store (X_features.parquet)
2. Recreates the train/test split from XGBoost training
3. Loads the fitted XGBoost model
4. Calls calibrate_model to fit the Platt sigmoid layer
5. Evaluates Gini and BrierSkill before and after calibration
6. Saves calibrated model and results JSON

Output:
  - models/xgboost_calibrated.pkl — calibrated wrapper
  - reports/xgboost_calibration_results.json — metrics
  - reports/figures/calibration_reliability.png — reliability diagram (generated by calibrate_model)
"""

import json
import sys
from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split

# Alias src as credit_engine for consistency with conftest.py
sys.path.insert(0, str(Path(__file__).parent.parent))
import src  # noqa: E402
sys.modules["credit_engine"] = src

from src.model import calibrate_model, load_model, save_model
from src.utils import gini_coefficient

# Constants
RANDOM_STATE = 42
FEATURE_STORE_PATH = "data/processed/X_features.parquet"
TARGET_PATH = "data/processed/y_train.parquet"
XGBOOST_MODEL_PATH = "models/xgboost_best.pkl"
CALIBRATED_MODEL_PATH = "models/xgboost_calibrated.pkl"
RESULTS_PATH = "reports/xgboost_calibration_results.json"


def main() -> None:
    """Run calibration workflow."""
    print("=" * 80)
    print("XGBoost Probability Calibration (Platt Scaling)")
    print("=" * 80)

    # --- Load feature store ---
    print("\n[1/6] Loading feature store...")
    X_final = pd.read_parquet(FEATURE_STORE_PATH)
    y = pd.read_parquet(TARGET_PATH).squeeze()
    print(f"  ✓ Loaded X: {X_final.shape}")
    print(f"  ✓ Loaded y: {y.shape}, target prevalence: {y.mean():.4f}")

    # --- Recreate train/test split ---
    print("\n[2/6] Recreating train/test split (test_size=0.2, random_state=42)...")
    X_train, X_test, y_train, y_test = train_test_split(
        X_final, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
    )
    print(f"  ✓ X_train: {X_train.shape}, y_train: {y_train.shape}")
    print(f"  ✓ X_test: {X_test.shape}, y_test: {y_test.shape}")

    # --- Load XGBoost model ---
    print("\n[3/6] Loading XGBoost model...")
    xgb_model = load_model(XGBOOST_MODEL_PATH)
    print(f"  ✓ Loaded model from {XGBOOST_MODEL_PATH}")

    # --- Compute baseline metrics (before calibration) ---
    print("\n[4/6] Computing baseline metrics (uncalibrated)...")
    y_prob_uncal = xgb_model.predict_proba(X_test)[:, 1]
    gini_uncal = gini_coefficient(y_test, y_prob_uncal)

    # Brier score before calibration
    from sklearn.metrics import brier_score_loss
    brier_uncal = float(brier_score_loss(y_test, y_prob_uncal))

    # BrierSkill: 1 - BS / (prevalence * (1 - prevalence))
    prevalence = y_test.mean()
    brier_skill_uncal = 1.0 - (brier_uncal / (prevalence * (1.0 - prevalence)))

    print(f"  ✓ Gini (uncalibrated): {gini_uncal:.6f}")
    print(f"  ✓ Brier (uncalibrated): {brier_uncal:.6f}")
    print(f"  ✓ BrierSkill (uncalibrated): {brier_skill_uncal:.6f}")

    # --- Calibrate model ---
    print("\n[5/6] Fitting Platt sigmoid calibration layer...")
    print(f"  (internal 70/30 split on X_train: 70% unused, 30% trains calibrator)")
    calibrated_model, brier_uncal_check, brier_cal = calibrate_model(
        xgb_model, X_train, y_train, X_test, y_test, method="sigmoid"
    )
    print(f"  ✓ Calibration complete. Brier improved: {brier_uncal:.6f} → {brier_cal:.6f}")

    # --- Compute calibrated metrics ---
    print("\n[6/6] Computing calibrated metrics...")
    y_prob_cal = calibrated_model.predict_proba(X_test)[:, 1]
    gini_cal = gini_coefficient(y_test, y_prob_cal)
    brier_skill_cal = 1.0 - (brier_cal / (prevalence * (1.0 - prevalence)))

    print(f"  ✓ Gini (calibrated): {gini_cal:.6f}")
    print(f"  ✓ Brier (calibrated): {brier_cal:.6f}")
    print(f"  ✓ BrierSkill (calibrated): {brier_skill_cal:.6f}")

    # --- Save calibrated model ---
    print(f"\n[7/7] Saving calibrated model to {CALIBRATED_MODEL_PATH}...")
    save_model(calibrated_model, CALIBRATED_MODEL_PATH)
    print(f"  ✓ Saved")

    # --- Save results JSON ---
    print(f"\nSaving results to {RESULTS_PATH}...")
    results = {
        "model": "XGBoost (Optuna-tuned)",
        "calibration_method": "sigmoid (Platt scaling)",
        "test_set_size": int(len(y_test)),
        "target_prevalence": float(prevalence),
        "gini_uncalibrated": float(gini_uncal),
        "gini_calibrated": float(gini_cal),
        "gini_improvement": float(gini_cal - gini_uncal),
        "brier_uncalibrated": float(brier_uncal),
        "brier_calibrated": float(brier_cal),
        "brier_improvement": float(brier_uncal - brier_cal),
        "brier_skill_uncalibrated": float(brier_skill_uncal),
        "brier_skill_calibrated": float(brier_skill_cal),
        "brier_skill_improvement": float(brier_skill_cal - brier_skill_uncal),
    }

    results_path = Path(RESULTS_PATH)
    results_path.parent.mkdir(parents=True, exist_ok=True)
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"  ✓ Results saved")

    # --- Summary ---
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"\nGini coefficient:")
    print(f"  Uncalibrated: {gini_uncal:.6f}")
    print(f"  Calibrated:   {gini_cal:.6f}")
    print(f"  Change:       {gini_cal - gini_uncal:+.6f}")

    print(f"\nBrier score (lower is better):")
    print(f"  Uncalibrated: {brier_uncal:.6f}")
    print(f"  Calibrated:   {brier_cal:.6f}")
    print(f"  Change:       {brier_uncal - brier_cal:+.6f}")

    print(f"\nBrierSkill (higher is better):")
    print(f"  Uncalibrated: {brier_skill_uncal:.6f}")
    print(f"  Calibrated:   {brier_skill_cal:.6f}")
    print(f"  Change:       {brier_skill_cal - brier_skill_uncal:+.6f}")

    print(f"\nArtifacts saved:")
    print(f"  Calibrated model: {CALIBRATED_MODEL_PATH}")
    print(f"  Results JSON:     {RESULTS_PATH}")
    print(f"  Reliability plot: reports/figures/calibration_reliability.png")
    print("\n" + "=" * 80)


if __name__ == "__main__":
    main()
